### ISSUE TITLE
truncate labels for x or y axis display at X characters

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/deriva-webapps#160]
In some configurations, the labels that are used for the x or y axis can be very long causing the chart to be displayed very small. We want to investigate the following:
 - Is there a way for us to tell plotly when to truncate axis labels? 
   - **how to truncate and show tooltip in plotly?**
   - **Do we need to include an index of terms that are truncated (similar to wikipedia "sources" section)**
 - Would we have to provide this truncation ourself before setting the terms for the axis labels?
   -  **What if we truncate after 10 characters, how would similar looking phrases be handled?**
     - `this is length of 20` -> `this is le...`
     - `this is length more than 20` -> `this is le...`
 - Property for truncation should be per axis, if plotly supports this already it will probably be under `layout.xaxis | yaxis`
   - if we have to override plotly, we'll add a property to `config.xaxis | yaxis`
   - **what should this property be called?**
   
 A good example to look at is the [study-violin]( https://dev.gudmap.org/deriva-webapps/plot/?config=study-violin). When the page loads select `Anatomical Source` from the Group By dropdown then `Select All` for the Study selector.
<img width="1479" alt="image" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/2932600/79d1df03-4495-4128-8ae2-ad54b9605cc8">

**Comment by KenyShah24** [comment]
- Initial approach - truncating the xticks if the number of characters were greater than 20 then truncate after 10 characters and show on xticks

**Comment by KenyShah24** [comment]
- Rethinking text truncation and addressing the space issue in the legend generated by Plotly
- Attempted to wrap text inside the legend to reduce its width
- Comparing the behavior of legend placement in AngularJS and ReactJS versions of the Plot app
- Noticing that the legend overlaps the plot content in AngularJS but squishes the plot area in ReactJS when resizing the window
- Trying to replicate the AngularJS behavior in the React version by placing the legend inside the plot when the window width is less than 1200 and keeping the orientation horizontal to reduce the overlapping due to the height of legend box
- Wrapping xticks to two lines and truncating each line after 25 characters.
- -> Drawbacks/Issues that were noticed while implementing:
- Identifying the legend overlap issue as a problem with an earlier version of Plotly, which was resolved in a later version
- Noting that Plotly keeps the legend vertical despite specifying a horizontal orientation due to long text in the legend

**Comment by KenyShah24** [comment]
Step function to decide the width of legend based on the plot's overall width:
1) legend size = 40%(of plot area width) when no. of violins are less than or equal to 7
![image (6)](https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/9da286a0-6d0e-49cf-9a63-855ff3b90e92)

2) legend size = 30%(of plot area width) when 8<=no. of violins<=30
![image](https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/f9aea82c-25a7-4223-9ab3-6cde0bc92b2c)

3) legend size = 15%(of plot area width) when no. of violins are greater than 30(For example, 47 in the given screen shot)
--> bigger screens (where it's not taking more than 30% of width)
![image](https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/ed630210-25e2-4171-a762-405d4ce6751a)

--> Normal screens (where it's taking more than 30% of width so reducing that to 15%)
![image](https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/5625b22d-1747-4e14-80d7-6d38747c9724)
