### ISSUE TITLE
plot config can come from anywhere on deployment

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/deriva-webapps#92]
Plot config can come from anywhere on the deployment, not just in the plot folder

**Comment by jrchudy** [comment]
I think this is _ALMOST_ possible now. We have a variable named `CONFIG` in the makefile that can be overridden using environment variables. This only allows the config to be installed to _any configured location_ but doesn't change the path defined in `webpack/main.config.js` to match the same defined config path from the environment variable.

@RFSH correct me if I'm wrong.

**Comment by RFSH** [comment]
The `CONFIG` variable is defined internally in `Makefile` and cannot be overridden. It's used in `deploy-w-config` commands which are only useful for developers. In actual deployments, we probably don't want to mix `deploy` with changing the config, and these would probably be two different processes (Just like they currently are in division recipes).

I'm not sure why we want to allow this and what benefit we get, but as you mentioned, we would just need to change the `webpack/main.config.js` to use an env variable instead of assuming `${WEBAPPS_BASE_PATH}config/plot-config.js`.

**Comment by jrchudy** [comment]
Another comment @hongsudt made about this was that the configuration could be a file stored in hatrac. This goes along with "allowing the config file to come from any location on the server".

The idea is that accessing and editing `*-config.js` is easier from hatrac than using ssh to connect to the server and modify in place or overwrite the existing config with an updated config.
